spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://106.15.189.14:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 106.15.189.14
#     username: guest
#     password: guest
#   redis:
#     host: 106.15.189.14
#     port: 6379
env:
  dev
girl:
  name: mo
  age: 17
# feign:
#   client:
#     config:
#       default:
#         connectTimeout: 5000
#         readTimeout: 5000
#         loggerLevel: basic  
